// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/skni-kod/iot-monitor-backend/services/sensor-service/ent/sensor"
	"github.com/skni-kod/iot-monitor-backend/services/sensor-service/ent/sensorgroup"
)

// SensorGroupCreate is the builder for creating a SensorGroup entity.
type SensorGroupCreate struct {
	config
	mutation *SensorGroupMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (sgc *SensorGroupCreate) SetName(s string) *SensorGroupCreate {
	sgc.mutation.SetName(s)
	return sgc
}

// SetDescription sets the "description" field.
func (sgc *SensorGroupCreate) SetDescription(s string) *SensorGroupCreate {
	sgc.mutation.SetDescription(s)
	return sgc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (sgc *SensorGroupCreate) SetNillableDescription(s *string) *SensorGroupCreate {
	if s != nil {
		sgc.SetDescription(*s)
	}
	return sgc
}

// SetColor sets the "color" field.
func (sgc *SensorGroupCreate) SetColor(s string) *SensorGroupCreate {
	sgc.mutation.SetColor(s)
	return sgc
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (sgc *SensorGroupCreate) SetNillableColor(s *string) *SensorGroupCreate {
	if s != nil {
		sgc.SetColor(*s)
	}
	return sgc
}

// SetIcon sets the "icon" field.
func (sgc *SensorGroupCreate) SetIcon(s string) *SensorGroupCreate {
	sgc.mutation.SetIcon(s)
	return sgc
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (sgc *SensorGroupCreate) SetNillableIcon(s *string) *SensorGroupCreate {
	if s != nil {
		sgc.SetIcon(*s)
	}
	return sgc
}

// SetUserID sets the "user_id" field.
func (sgc *SensorGroupCreate) SetUserID(i int64) *SensorGroupCreate {
	sgc.mutation.SetUserID(i)
	return sgc
}

// SetCreatedAt sets the "created_at" field.
func (sgc *SensorGroupCreate) SetCreatedAt(t time.Time) *SensorGroupCreate {
	sgc.mutation.SetCreatedAt(t)
	return sgc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sgc *SensorGroupCreate) SetNillableCreatedAt(t *time.Time) *SensorGroupCreate {
	if t != nil {
		sgc.SetCreatedAt(*t)
	}
	return sgc
}

// SetUpdatedAt sets the "updated_at" field.
func (sgc *SensorGroupCreate) SetUpdatedAt(t time.Time) *SensorGroupCreate {
	sgc.mutation.SetUpdatedAt(t)
	return sgc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (sgc *SensorGroupCreate) SetNillableUpdatedAt(t *time.Time) *SensorGroupCreate {
	if t != nil {
		sgc.SetUpdatedAt(*t)
	}
	return sgc
}

// AddSensorIDs adds the "sensors" edge to the Sensor entity by IDs.
func (sgc *SensorGroupCreate) AddSensorIDs(ids ...int) *SensorGroupCreate {
	sgc.mutation.AddSensorIDs(ids...)
	return sgc
}

// AddSensors adds the "sensors" edges to the Sensor entity.
func (sgc *SensorGroupCreate) AddSensors(s ...*Sensor) *SensorGroupCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return sgc.AddSensorIDs(ids...)
}

// Mutation returns the SensorGroupMutation object of the builder.
func (sgc *SensorGroupCreate) Mutation() *SensorGroupMutation {
	return sgc.mutation
}

// Save creates the SensorGroup in the database.
func (sgc *SensorGroupCreate) Save(ctx context.Context) (*SensorGroup, error) {
	sgc.defaults()
	return withHooks(ctx, sgc.sqlSave, sgc.mutation, sgc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sgc *SensorGroupCreate) SaveX(ctx context.Context) *SensorGroup {
	v, err := sgc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sgc *SensorGroupCreate) Exec(ctx context.Context) error {
	_, err := sgc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sgc *SensorGroupCreate) ExecX(ctx context.Context) {
	if err := sgc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sgc *SensorGroupCreate) defaults() {
	if _, ok := sgc.mutation.Color(); !ok {
		v := sensorgroup.DefaultColor
		sgc.mutation.SetColor(v)
	}
	if _, ok := sgc.mutation.CreatedAt(); !ok {
		v := sensorgroup.DefaultCreatedAt()
		sgc.mutation.SetCreatedAt(v)
	}
	if _, ok := sgc.mutation.UpdatedAt(); !ok {
		v := sensorgroup.DefaultUpdatedAt()
		sgc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sgc *SensorGroupCreate) check() error {
	if _, ok := sgc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SensorGroup.name"`)}
	}
	if v, ok := sgc.mutation.Name(); ok {
		if err := sensorgroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SensorGroup.name": %w`, err)}
		}
	}
	if _, ok := sgc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "SensorGroup.user_id"`)}
	}
	if _, ok := sgc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SensorGroup.created_at"`)}
	}
	if _, ok := sgc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SensorGroup.updated_at"`)}
	}
	return nil
}

func (sgc *SensorGroupCreate) sqlSave(ctx context.Context) (*SensorGroup, error) {
	if err := sgc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sgc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sgc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sgc.mutation.id = &_node.ID
	sgc.mutation.done = true
	return _node, nil
}

func (sgc *SensorGroupCreate) createSpec() (*SensorGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &SensorGroup{config: sgc.config}
		_spec = sqlgraph.NewCreateSpec(sensorgroup.Table, sqlgraph.NewFieldSpec(sensorgroup.FieldID, field.TypeInt))
	)
	if value, ok := sgc.mutation.Name(); ok {
		_spec.SetField(sensorgroup.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := sgc.mutation.Description(); ok {
		_spec.SetField(sensorgroup.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := sgc.mutation.Color(); ok {
		_spec.SetField(sensorgroup.FieldColor, field.TypeString, value)
		_node.Color = value
	}
	if value, ok := sgc.mutation.Icon(); ok {
		_spec.SetField(sensorgroup.FieldIcon, field.TypeString, value)
		_node.Icon = value
	}
	if value, ok := sgc.mutation.UserID(); ok {
		_spec.SetField(sensorgroup.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := sgc.mutation.CreatedAt(); ok {
		_spec.SetField(sensorgroup.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := sgc.mutation.UpdatedAt(); ok {
		_spec.SetField(sensorgroup.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := sgc.mutation.SensorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   sensorgroup.SensorsTable,
			Columns: sensorgroup.SensorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sensor.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SensorGroupCreateBulk is the builder for creating many SensorGroup entities in bulk.
type SensorGroupCreateBulk struct {
	config
	err      error
	builders []*SensorGroupCreate
}

// Save creates the SensorGroup entities in the database.
func (sgcb *SensorGroupCreateBulk) Save(ctx context.Context) ([]*SensorGroup, error) {
	if sgcb.err != nil {
		return nil, sgcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(sgcb.builders))
	nodes := make([]*SensorGroup, len(sgcb.builders))
	mutators := make([]Mutator, len(sgcb.builders))
	for i := range sgcb.builders {
		func(i int, root context.Context) {
			builder := sgcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SensorGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, sgcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, sgcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, sgcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (sgcb *SensorGroupCreateBulk) SaveX(ctx context.Context) []*SensorGroup {
	v, err := sgcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sgcb *SensorGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := sgcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sgcb *SensorGroupCreateBulk) ExecX(ctx context.Context) {
	if err := sgcb.Exec(ctx); err != nil {
		panic(err)
	}
}
