// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: data_service.proto

package data_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataService_StoreReading_FullMethodName      = "/data_service.DataService/StoreReading"
	DataService_QueryReadings_FullMethodName     = "/data_service.DataService/QueryReadings"
	DataService_StreamReadings_FullMethodName    = "/data_service.DataService/StreamReadings"
	DataService_GetLatestReadings_FullMethodName = "/data_service.DataService/GetLatestReadings"
)

// DataServiceClient is the client API for DataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataServiceClient interface {
	StoreReading(ctx context.Context, in *StoreReadingRequest, opts ...grpc.CallOption) (*StoreReadingResponse, error)
	QueryReadings(ctx context.Context, in *QueryReadingsRequest, opts ...grpc.CallOption) (*QueryReadingsResponse, error)
	StreamReadings(ctx context.Context, in *StreamReadingsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadingUpdate], error)
	GetLatestReadings(ctx context.Context, in *LatestReadingsRequest, opts ...grpc.CallOption) (*LatestReadingsResponse, error)
}

type dataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataServiceClient(cc grpc.ClientConnInterface) DataServiceClient {
	return &dataServiceClient{cc}
}

func (c *dataServiceClient) StoreReading(ctx context.Context, in *StoreReadingRequest, opts ...grpc.CallOption) (*StoreReadingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreReadingResponse)
	err := c.cc.Invoke(ctx, DataService_StoreReading_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) QueryReadings(ctx context.Context, in *QueryReadingsRequest, opts ...grpc.CallOption) (*QueryReadingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryReadingsResponse)
	err := c.cc.Invoke(ctx, DataService_QueryReadings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) StreamReadings(ctx context.Context, in *StreamReadingsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadingUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataService_ServiceDesc.Streams[0], DataService_StreamReadings_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamReadingsRequest, ReadingUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataService_StreamReadingsClient = grpc.ServerStreamingClient[ReadingUpdate]

func (c *dataServiceClient) GetLatestReadings(ctx context.Context, in *LatestReadingsRequest, opts ...grpc.CallOption) (*LatestReadingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LatestReadingsResponse)
	err := c.cc.Invoke(ctx, DataService_GetLatestReadings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataServiceServer is the server API for DataService service.
// All implementations must embed UnimplementedDataServiceServer
// for forward compatibility.
type DataServiceServer interface {
	StoreReading(context.Context, *StoreReadingRequest) (*StoreReadingResponse, error)
	QueryReadings(context.Context, *QueryReadingsRequest) (*QueryReadingsResponse, error)
	StreamReadings(*StreamReadingsRequest, grpc.ServerStreamingServer[ReadingUpdate]) error
	GetLatestReadings(context.Context, *LatestReadingsRequest) (*LatestReadingsResponse, error)
	mustEmbedUnimplementedDataServiceServer()
}

// UnimplementedDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataServiceServer struct{}

func (UnimplementedDataServiceServer) StoreReading(context.Context, *StoreReadingRequest) (*StoreReadingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreReading not implemented")
}
func (UnimplementedDataServiceServer) QueryReadings(context.Context, *QueryReadingsRequest) (*QueryReadingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryReadings not implemented")
}
func (UnimplementedDataServiceServer) StreamReadings(*StreamReadingsRequest, grpc.ServerStreamingServer[ReadingUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method StreamReadings not implemented")
}
func (UnimplementedDataServiceServer) GetLatestReadings(context.Context, *LatestReadingsRequest) (*LatestReadingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestReadings not implemented")
}
func (UnimplementedDataServiceServer) mustEmbedUnimplementedDataServiceServer() {}
func (UnimplementedDataServiceServer) testEmbeddedByValue()                     {}

// UnsafeDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataServiceServer will
// result in compilation errors.
type UnsafeDataServiceServer interface {
	mustEmbedUnimplementedDataServiceServer()
}

func RegisterDataServiceServer(s grpc.ServiceRegistrar, srv DataServiceServer) {
	// If the following call pancis, it indicates UnimplementedDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataService_ServiceDesc, srv)
}

func _DataService_StoreReading_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreReadingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).StoreReading(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_StoreReading_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).StoreReading(ctx, req.(*StoreReadingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_QueryReadings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryReadingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).QueryReadings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_QueryReadings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).QueryReadings(ctx, req.(*QueryReadingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_StreamReadings_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamReadingsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataServiceServer).StreamReadings(m, &grpc.GenericServerStream[StreamReadingsRequest, ReadingUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataService_StreamReadingsServer = grpc.ServerStreamingServer[ReadingUpdate]

func _DataService_GetLatestReadings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LatestReadingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).GetLatestReadings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_GetLatestReadings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).GetLatestReadings(ctx, req.(*LatestReadingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataService_ServiceDesc is the grpc.ServiceDesc for DataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "data_service.DataService",
	HandlerType: (*DataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreReading",
			Handler:    _DataService_StoreReading_Handler,
		},
		{
			MethodName: "QueryReadings",
			Handler:    _DataService_QueryReadings_Handler,
		},
		{
			MethodName: "GetLatestReadings",
			Handler:    _DataService_GetLatestReadings_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamReadings",
			Handler:       _DataService_StreamReadings_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "data_service.proto",
}
