// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: data_service.proto

package data_service

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreReadingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SensorId      int64                  `protobuf:"varint,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	Value         float32                `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreReadingRequest) Reset() {
	*x = StoreReadingRequest{}
	mi := &file_data_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreReadingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreReadingRequest) ProtoMessage() {}

func (x *StoreReadingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreReadingRequest.ProtoReflect.Descriptor instead.
func (*StoreReadingRequest) Descriptor() ([]byte, []int) {
	return file_data_service_proto_rawDescGZIP(), []int{0}
}

func (x *StoreReadingRequest) GetSensorId() int64 {
	if x != nil {
		return x.SensorId
	}
	return 0
}

func (x *StoreReadingRequest) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *StoreReadingRequest) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type StoreReadingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreReadingResponse) Reset() {
	*x = StoreReadingResponse{}
	mi := &file_data_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreReadingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreReadingResponse) ProtoMessage() {}

func (x *StoreReadingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreReadingResponse.ProtoReflect.Descriptor instead.
func (*StoreReadingResponse) Descriptor() ([]byte, []int) {
	return file_data_service_proto_rawDescGZIP(), []int{1}
}

type QueryReadingsRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SensorId            int64                  `protobuf:"varint,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	StartTime           *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime             *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	AggregationInterval string                 `protobuf:"bytes,4,opt,name=aggregation_interval,json=aggregationInterval,proto3" json:"aggregation_interval,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *QueryReadingsRequest) Reset() {
	*x = QueryReadingsRequest{}
	mi := &file_data_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryReadingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryReadingsRequest) ProtoMessage() {}

func (x *QueryReadingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryReadingsRequest.ProtoReflect.Descriptor instead.
func (*QueryReadingsRequest) Descriptor() ([]byte, []int) {
	return file_data_service_proto_rawDescGZIP(), []int{2}
}

func (x *QueryReadingsRequest) GetSensorId() int64 {
	if x != nil {
		return x.SensorId
	}
	return 0
}

func (x *QueryReadingsRequest) GetStartTime() *timestamp.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *QueryReadingsRequest) GetEndTime() *timestamp.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *QueryReadingsRequest) GetAggregationInterval() string {
	if x != nil {
		return x.AggregationInterval
	}
	return ""
}

type DataPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamp.Timestamp   `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Value         float32                `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPoint) Reset() {
	*x = DataPoint{}
	mi := &file_data_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPoint) ProtoMessage() {}

func (x *DataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_data_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPoint.ProtoReflect.Descriptor instead.
func (*DataPoint) Descriptor() ([]byte, []int) {
	return file_data_service_proto_rawDescGZIP(), []int{3}
}

func (x *DataPoint) GetTime() *timestamp.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *DataPoint) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type QueryReadingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataPoints    []*DataPoint           `protobuf:"bytes,1,rep,name=data_points,json=dataPoints,proto3" json:"data_points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryReadingsResponse) Reset() {
	*x = QueryReadingsResponse{}
	mi := &file_data_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryReadingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryReadingsResponse) ProtoMessage() {}

func (x *QueryReadingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryReadingsResponse.ProtoReflect.Descriptor instead.
func (*QueryReadingsResponse) Descriptor() ([]byte, []int) {
	return file_data_service_proto_rawDescGZIP(), []int{4}
}

func (x *QueryReadingsResponse) GetDataPoints() []*DataPoint {
	if x != nil {
		return x.DataPoints
	}
	return nil
}

type StreamReadingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SensorIds     []int64                `protobuf:"varint,1,rep,packed,name=sensor_ids,json=sensorIds,proto3" json:"sensor_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamReadingsRequest) Reset() {
	*x = StreamReadingsRequest{}
	mi := &file_data_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamReadingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamReadingsRequest) ProtoMessage() {}

func (x *StreamReadingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamReadingsRequest.ProtoReflect.Descriptor instead.
func (*StreamReadingsRequest) Descriptor() ([]byte, []int) {
	return file_data_service_proto_rawDescGZIP(), []int{5}
}

func (x *StreamReadingsRequest) GetSensorIds() []int64 {
	if x != nil {
		return x.SensorIds
	}
	return nil
}

type ReadingUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SensorId      int64                  `protobuf:"varint,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	Value         float32                `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SensorName    string                 `protobuf:"bytes,4,opt,name=sensor_name,json=sensorName,proto3" json:"sensor_name,omitempty"`
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Unit          string                 `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadingUpdate) Reset() {
	*x = ReadingUpdate{}
	mi := &file_data_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadingUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadingUpdate) ProtoMessage() {}

func (x *ReadingUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_data_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadingUpdate.ProtoReflect.Descriptor instead.
func (*ReadingUpdate) Descriptor() ([]byte, []int) {
	return file_data_service_proto_rawDescGZIP(), []int{6}
}

func (x *ReadingUpdate) GetSensorId() int64 {
	if x != nil {
		return x.SensorId
	}
	return 0
}

func (x *ReadingUpdate) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ReadingUpdate) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ReadingUpdate) GetSensorName() string {
	if x != nil {
		return x.SensorName
	}
	return ""
}

func (x *ReadingUpdate) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ReadingUpdate) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type LatestReadingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SensorIds     []int64                `protobuf:"varint,1,rep,packed,name=sensor_ids,json=sensorIds,proto3" json:"sensor_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatestReadingsRequest) Reset() {
	*x = LatestReadingsRequest{}
	mi := &file_data_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestReadingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestReadingsRequest) ProtoMessage() {}

func (x *LatestReadingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestReadingsRequest.ProtoReflect.Descriptor instead.
func (*LatestReadingsRequest) Descriptor() ([]byte, []int) {
	return file_data_service_proto_rawDescGZIP(), []int{7}
}

func (x *LatestReadingsRequest) GetSensorIds() []int64 {
	if x != nil {
		return x.SensorIds
	}
	return nil
}

type LatestReading struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SensorId      int64                  `protobuf:"varint,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	Value         float32                `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatestReading) Reset() {
	*x = LatestReading{}
	mi := &file_data_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestReading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestReading) ProtoMessage() {}

func (x *LatestReading) ProtoReflect() protoreflect.Message {
	mi := &file_data_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestReading.ProtoReflect.Descriptor instead.
func (*LatestReading) Descriptor() ([]byte, []int) {
	return file_data_service_proto_rawDescGZIP(), []int{8}
}

func (x *LatestReading) GetSensorId() int64 {
	if x != nil {
		return x.SensorId
	}
	return 0
}

func (x *LatestReading) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *LatestReading) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type LatestReadingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Readings      []*LatestReading       `protobuf:"bytes,1,rep,name=readings,proto3" json:"readings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatestReadingsResponse) Reset() {
	*x = LatestReadingsResponse{}
	mi := &file_data_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestReadingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestReadingsResponse) ProtoMessage() {}

func (x *LatestReadingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestReadingsResponse.ProtoReflect.Descriptor instead.
func (*LatestReadingsResponse) Descriptor() ([]byte, []int) {
	return file_data_service_proto_rawDescGZIP(), []int{9}
}

func (x *LatestReadingsResponse) GetReadings() []*LatestReading {
	if x != nil {
		return x.Readings
	}
	return nil
}

var File_data_service_proto protoreflect.FileDescriptor

const file_data_service_proto_rawDesc = "" +
	"\n" +
	"\x12data_service.proto\x12\fdata_service\x1a\x1fgoogle/protobuf/timestamp.proto\"\x82\x01\n" +
	"\x13StoreReadingRequest\x12\x1b\n" +
	"\tsensor_id\x18\x01 \x01(\x03R\bsensorId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x16\n" +
	"\x14StoreReadingResponse\"\xd8\x01\n" +
	"\x14QueryReadingsRequest\x12\x1b\n" +
	"\tsensor_id\x18\x01 \x01(\x03R\bsensorId\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x121\n" +
	"\x14aggregation_interval\x18\x04 \x01(\tR\x13aggregationInterval\"Q\n" +
	"\tDataPoint\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value\"Q\n" +
	"\x15QueryReadingsResponse\x128\n" +
	"\vdata_points\x18\x01 \x03(\v2\x17.data_service.DataPointR\n" +
	"dataPoints\"6\n" +
	"\x15StreamReadingsRequest\x12\x1d\n" +
	"\n" +
	"sensor_ids\x18\x01 \x03(\x03R\tsensorIds\"\xcd\x01\n" +
	"\rReadingUpdate\x12\x1b\n" +
	"\tsensor_id\x18\x01 \x01(\x03R\bsensorId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1f\n" +
	"\vsensor_name\x18\x04 \x01(\tR\n" +
	"sensorName\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12\x12\n" +
	"\x04unit\x18\x06 \x01(\tR\x04unit\"6\n" +
	"\x15LatestReadingsRequest\x12\x1d\n" +
	"\n" +
	"sensor_ids\x18\x01 \x03(\x03R\tsensorIds\"|\n" +
	"\rLatestReading\x12\x1b\n" +
	"\tsensor_id\x18\x01 \x01(\x03R\bsensorId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"Q\n" +
	"\x16LatestReadingsResponse\x127\n" +
	"\breadings\x18\x01 \x03(\v2\x1b.data_service.LatestReadingR\breadings2\xfc\x02\n" +
	"\vDataService\x12W\n" +
	"\fStoreReading\x12!.data_service.StoreReadingRequest\x1a\".data_service.StoreReadingResponse\"\x00\x12Z\n" +
	"\rQueryReadings\x12\".data_service.QueryReadingsRequest\x1a#.data_service.QueryReadingsResponse\"\x00\x12V\n" +
	"\x0eStreamReadings\x12#.data_service.StreamReadingsRequest\x1a\x1b.data_service.ReadingUpdate\"\x000\x01\x12`\n" +
	"\x11GetLatestReadings\x12#.data_service.LatestReadingsRequest\x1a$.data_service.LatestReadingsResponse\"\x00BEZCgithub.com/skni-kod/iot-monitor-backend/internal/proto/data_serviceb\x06proto3"

var (
	file_data_service_proto_rawDescOnce sync.Once
	file_data_service_proto_rawDescData []byte
)

func file_data_service_proto_rawDescGZIP() []byte {
	file_data_service_proto_rawDescOnce.Do(func() {
		file_data_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_service_proto_rawDesc), len(file_data_service_proto_rawDesc)))
	})
	return file_data_service_proto_rawDescData
}

var file_data_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_data_service_proto_goTypes = []any{
	(*StoreReadingRequest)(nil),    // 0: data_service.StoreReadingRequest
	(*StoreReadingResponse)(nil),   // 1: data_service.StoreReadingResponse
	(*QueryReadingsRequest)(nil),   // 2: data_service.QueryReadingsRequest
	(*DataPoint)(nil),              // 3: data_service.DataPoint
	(*QueryReadingsResponse)(nil),  // 4: data_service.QueryReadingsResponse
	(*StreamReadingsRequest)(nil),  // 5: data_service.StreamReadingsRequest
	(*ReadingUpdate)(nil),          // 6: data_service.ReadingUpdate
	(*LatestReadingsRequest)(nil),  // 7: data_service.LatestReadingsRequest
	(*LatestReading)(nil),          // 8: data_service.LatestReading
	(*LatestReadingsResponse)(nil), // 9: data_service.LatestReadingsResponse
	(*timestamp.Timestamp)(nil),    // 10: google.protobuf.Timestamp
}
var file_data_service_proto_depIdxs = []int32{
	10, // 0: data_service.StoreReadingRequest.timestamp:type_name -> google.protobuf.Timestamp
	10, // 1: data_service.QueryReadingsRequest.start_time:type_name -> google.protobuf.Timestamp
	10, // 2: data_service.QueryReadingsRequest.end_time:type_name -> google.protobuf.Timestamp
	10, // 3: data_service.DataPoint.time:type_name -> google.protobuf.Timestamp
	3,  // 4: data_service.QueryReadingsResponse.data_points:type_name -> data_service.DataPoint
	10, // 5: data_service.ReadingUpdate.timestamp:type_name -> google.protobuf.Timestamp
	10, // 6: data_service.LatestReading.timestamp:type_name -> google.protobuf.Timestamp
	8,  // 7: data_service.LatestReadingsResponse.readings:type_name -> data_service.LatestReading
	0,  // 8: data_service.DataService.StoreReading:input_type -> data_service.StoreReadingRequest
	2,  // 9: data_service.DataService.QueryReadings:input_type -> data_service.QueryReadingsRequest
	5,  // 10: data_service.DataService.StreamReadings:input_type -> data_service.StreamReadingsRequest
	7,  // 11: data_service.DataService.GetLatestReadings:input_type -> data_service.LatestReadingsRequest
	1,  // 12: data_service.DataService.StoreReading:output_type -> data_service.StoreReadingResponse
	4,  // 13: data_service.DataService.QueryReadings:output_type -> data_service.QueryReadingsResponse
	6,  // 14: data_service.DataService.StreamReadings:output_type -> data_service.ReadingUpdate
	9,  // 15: data_service.DataService.GetLatestReadings:output_type -> data_service.LatestReadingsResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_data_service_proto_init() }
func file_data_service_proto_init() {
	if File_data_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_service_proto_rawDesc), len(file_data_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_service_proto_goTypes,
		DependencyIndexes: file_data_service_proto_depIdxs,
		MessageInfos:      file_data_service_proto_msgTypes,
	}.Build()
	File_data_service_proto = out.File
	file_data_service_proto_goTypes = nil
	file_data_service_proto_depIdxs = nil
}
