version: "2"

linters:
  default: standard
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
      disable-default-exclusions: true
      exclude-functions:
        - (net/http.ResponseWriter).Write
        - (net/http).ListenAndServe
        - (ent.Client).Close

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines

issues:
  max-issues-per-linter: 50
  max-same-issues: 3
  new: false
  fix: false
  uniq-by-line: true
  whole-files: false

run:
  timeout: "1m"
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: false
  allow-serial-runners: false
  go: "1.17"
  relative-path-mode: wd
