version: "2"
run:
  go: "1.24"
  issues-exit-code: 1
  tests: true
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    misspell:
      ignore-words:
        - nowe
    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - (net/http.ResponseWriter).Write
        - (*database/sql.DB).Close
        - (*database/sql.Rows).Close
        - (*google.golang.org/grpc.ClientConn).Close
        - (*encoding/json.Encoder).Encode
        - github.com/skni-kod/iot-monitor-backend/pkg/logger.Sync
        - github.com/go-chi/chi/v5.Walk
        - (*github.com/skni-kod/iot-monitor-backend/services/sensor-service/ent.Tx).Rollback
        - fmt.Sscanf
        - (*os.File).Close
        - (*github.com/gorilla/websocket.Conn).Close
        - encoding/json.Unmarshal
        - github.com/skni-kod/iot-monitor-backend/pkg/logger.Init
        - (*github.com/skni-kod/iot-monitor-backend/services/auth/ent.Client).Close
        - (*github.com/skni-kod/iot-monitor-backend/services/sensor-service/ent.Client).Close
        - (*github.com/skni-kod/iot-monitor-backend/services/alert-service/ent.Client).Close
        - (*google.golang.org/grpc.ClientConn).Close
        - (*github.com/rabbitmq/amqp091-go.Connection).Close
        - (*github.com/rabbitmq/amqp091-go.Channel).Close
    govet:
      enable:
        - assign
        - atomic
        - bools
        - buildtag
        - composites
        - copylocks
        - errorsas
        - httpresponse
        - loopclosure
        - lostcancel
        - nilfunc
        - printf
        - shift
        - stdmethods
        - structtag
        - tests
        - unmarshal
        - unreachable
        - unsafeptr
        - unusedresult
    revive:
      severity: warning
      rules:
        - name: exported
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - unparam
        path: _test\.go
      - linters:
          - all
        path: \.pb\.go$
      - linters:
          - all
        path: ent/
      - linters:
          - errcheck
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
