#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<-EOSQL

    CREATE USER $AUTH_SERVICE_DB_USER WITH PASSWORD '$AUTH_SERVICE_DB_PASSWORD';
    CREATE DATABASE $AUTH_SERVICE_DB_NAME;
    ALTER DATABASE $AUTH_SERVICE_DB_NAME OWNER TO $AUTH_SERVICE_DB_USER;

    CREATE USER $SENSOR_SERVICE_DB_USER WITH PASSWORD '$SENSOR_SERVICE_DB_PASSWORD';
    CREATE DATABASE $SENSOR_SERVICE_DB_NAME;
    ALTER DATABASE $SENSOR_SERVICE_DB_NAME OWNER TO $SENSOR_SERVICE_DB_USER;

EOSQL