// Code generated by ent, DO NOT EDIT.

package alertrule

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/skni-kod/iot-monitor-backend/services/alert-service/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldEQ(FieldName, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldEQ(FieldUserID, v))
}

// SensorID applies equality check predicate on the "sensor_id" field. It's identical to SensorIDEQ.
func SensorID(v int64) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldEQ(FieldSensorID, v))
}

// ConditionType applies equality check predicate on the "condition_type" field. It's identical to ConditionTypeEQ.
func ConditionType(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldEQ(FieldConditionType, v))
}

// Threshold applies equality check predicate on the "threshold" field. It's identical to ThresholdEQ.
func Threshold(v float64) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldEQ(FieldThreshold, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldEQ(FieldDescription, v))
}

// IsEnabled applies equality check predicate on the "is_enabled" field. It's identical to IsEnabledEQ.
func IsEnabled(v bool) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldEQ(FieldIsEnabled, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldEQ(FieldCreatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldContainsFold(FieldName, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldLTE(FieldUserID, v))
}

// SensorIDEQ applies the EQ predicate on the "sensor_id" field.
func SensorIDEQ(v int64) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldEQ(FieldSensorID, v))
}

// SensorIDNEQ applies the NEQ predicate on the "sensor_id" field.
func SensorIDNEQ(v int64) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldNEQ(FieldSensorID, v))
}

// SensorIDIn applies the In predicate on the "sensor_id" field.
func SensorIDIn(vs ...int64) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldIn(FieldSensorID, vs...))
}

// SensorIDNotIn applies the NotIn predicate on the "sensor_id" field.
func SensorIDNotIn(vs ...int64) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldNotIn(FieldSensorID, vs...))
}

// SensorIDGT applies the GT predicate on the "sensor_id" field.
func SensorIDGT(v int64) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldGT(FieldSensorID, v))
}

// SensorIDGTE applies the GTE predicate on the "sensor_id" field.
func SensorIDGTE(v int64) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldGTE(FieldSensorID, v))
}

// SensorIDLT applies the LT predicate on the "sensor_id" field.
func SensorIDLT(v int64) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldLT(FieldSensorID, v))
}

// SensorIDLTE applies the LTE predicate on the "sensor_id" field.
func SensorIDLTE(v int64) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldLTE(FieldSensorID, v))
}

// ConditionTypeEQ applies the EQ predicate on the "condition_type" field.
func ConditionTypeEQ(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldEQ(FieldConditionType, v))
}

// ConditionTypeNEQ applies the NEQ predicate on the "condition_type" field.
func ConditionTypeNEQ(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldNEQ(FieldConditionType, v))
}

// ConditionTypeIn applies the In predicate on the "condition_type" field.
func ConditionTypeIn(vs ...string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldIn(FieldConditionType, vs...))
}

// ConditionTypeNotIn applies the NotIn predicate on the "condition_type" field.
func ConditionTypeNotIn(vs ...string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldNotIn(FieldConditionType, vs...))
}

// ConditionTypeGT applies the GT predicate on the "condition_type" field.
func ConditionTypeGT(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldGT(FieldConditionType, v))
}

// ConditionTypeGTE applies the GTE predicate on the "condition_type" field.
func ConditionTypeGTE(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldGTE(FieldConditionType, v))
}

// ConditionTypeLT applies the LT predicate on the "condition_type" field.
func ConditionTypeLT(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldLT(FieldConditionType, v))
}

// ConditionTypeLTE applies the LTE predicate on the "condition_type" field.
func ConditionTypeLTE(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldLTE(FieldConditionType, v))
}

// ConditionTypeContains applies the Contains predicate on the "condition_type" field.
func ConditionTypeContains(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldContains(FieldConditionType, v))
}

// ConditionTypeHasPrefix applies the HasPrefix predicate on the "condition_type" field.
func ConditionTypeHasPrefix(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldHasPrefix(FieldConditionType, v))
}

// ConditionTypeHasSuffix applies the HasSuffix predicate on the "condition_type" field.
func ConditionTypeHasSuffix(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldHasSuffix(FieldConditionType, v))
}

// ConditionTypeEqualFold applies the EqualFold predicate on the "condition_type" field.
func ConditionTypeEqualFold(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldEqualFold(FieldConditionType, v))
}

// ConditionTypeContainsFold applies the ContainsFold predicate on the "condition_type" field.
func ConditionTypeContainsFold(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldContainsFold(FieldConditionType, v))
}

// ThresholdEQ applies the EQ predicate on the "threshold" field.
func ThresholdEQ(v float64) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldEQ(FieldThreshold, v))
}

// ThresholdNEQ applies the NEQ predicate on the "threshold" field.
func ThresholdNEQ(v float64) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldNEQ(FieldThreshold, v))
}

// ThresholdIn applies the In predicate on the "threshold" field.
func ThresholdIn(vs ...float64) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldIn(FieldThreshold, vs...))
}

// ThresholdNotIn applies the NotIn predicate on the "threshold" field.
func ThresholdNotIn(vs ...float64) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldNotIn(FieldThreshold, vs...))
}

// ThresholdGT applies the GT predicate on the "threshold" field.
func ThresholdGT(v float64) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldGT(FieldThreshold, v))
}

// ThresholdGTE applies the GTE predicate on the "threshold" field.
func ThresholdGTE(v float64) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldGTE(FieldThreshold, v))
}

// ThresholdLT applies the LT predicate on the "threshold" field.
func ThresholdLT(v float64) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldLT(FieldThreshold, v))
}

// ThresholdLTE applies the LTE predicate on the "threshold" field.
func ThresholdLTE(v float64) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldLTE(FieldThreshold, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.AlertRule {
	return predicate.AlertRule(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.AlertRule {
	return predicate.AlertRule(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldContainsFold(FieldDescription, v))
}

// IsEnabledEQ applies the EQ predicate on the "is_enabled" field.
func IsEnabledEQ(v bool) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldEQ(FieldIsEnabled, v))
}

// IsEnabledNEQ applies the NEQ predicate on the "is_enabled" field.
func IsEnabledNEQ(v bool) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldNEQ(FieldIsEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AlertRule {
	return predicate.AlertRule(sql.FieldLTE(FieldCreatedAt, v))
}

// HasAlerts applies the HasEdge predicate on the "alerts" edge.
func HasAlerts() predicate.AlertRule {
	return predicate.AlertRule(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AlertsTable, AlertsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAlertsWith applies the HasEdge predicate on the "alerts" edge with a given conditions (other predicates).
func HasAlertsWith(preds ...predicate.Alert) predicate.AlertRule {
	return predicate.AlertRule(func(s *sql.Selector) {
		step := newAlertsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AlertRule) predicate.AlertRule {
	return predicate.AlertRule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AlertRule) predicate.AlertRule {
	return predicate.AlertRule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AlertRule) predicate.AlertRule {
	return predicate.AlertRule(sql.NotPredicates(p))
}
