// Code generated by ent, DO NOT EDIT.

package sensorgroup

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the sensorgroup type in the database.
	Label = "sensor_group"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldColor holds the string denoting the color field in the database.
	FieldColor = "color"
	// FieldIcon holds the string denoting the icon field in the database.
	FieldIcon = "icon"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeSensors holds the string denoting the sensors edge name in mutations.
	EdgeSensors = "sensors"
	// Table holds the table name of the sensorgroup in the database.
	Table = "sensor_groups"
	// SensorsTable is the table that holds the sensors relation/edge. The primary key declared below.
	SensorsTable = "sensor_group_sensors"
	// SensorsInverseTable is the table name for the Sensor entity.
	// It exists in this package in order to avoid circular dependency with the "sensor" package.
	SensorsInverseTable = "sensors"
)

// Columns holds all SQL columns for sensorgroup fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldColor,
	FieldIcon,
	FieldUserID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// SensorsPrimaryKey and SensorsColumn2 are the table columns denoting the
	// primary key for the sensors relation (M2M).
	SensorsPrimaryKey = []string{"sensor_group_id", "sensor_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultColor holds the default value on creation for the "color" field.
	DefaultColor string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the SensorGroup queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByColor orders the results by the color field.
func ByColor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldColor, opts...).ToFunc()
}

// ByIcon orders the results by the icon field.
func ByIcon(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIcon, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySensorsCount orders the results by sensors count.
func BySensorsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSensorsStep(), opts...)
	}
}

// BySensors orders the results by sensors terms.
func BySensors(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSensorsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSensorsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SensorsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, SensorsTable, SensorsPrimaryKey...),
	)
}
