// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: alert_service.proto

package alert_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RuleId        int64                  `protobuf:"varint,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	SensorId      int64                  `protobuf:"varint,3,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Value         float64                `protobuf:"fixed64,5,opt,name=value,proto3" json:"value,omitempty"`
	IsRead        bool                   `protobuf:"varint,6,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	TriggeredAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=triggered_at,json=triggeredAt,proto3" json:"triggered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_alert_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_alert_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_alert_service_proto_rawDescGZIP(), []int{0}
}

func (x *Alert) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Alert) GetRuleId() int64 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

func (x *Alert) GetSensorId() int64 {
	if x != nil {
		return x.SensorId
	}
	return 0
}

func (x *Alert) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Alert) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Alert) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *Alert) GetTriggeredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TriggeredAt
	}
	return nil
}

type GetAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertRequest) Reset() {
	*x = GetAlertRequest{}
	mi := &file_alert_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertRequest) ProtoMessage() {}

func (x *GetAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertRequest.ProtoReflect.Descriptor instead.
func (*GetAlertRequest) Descriptor() ([]byte, []int) {
	return file_alert_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetAlertRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAlertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alert         *Alert                 `protobuf:"bytes,1,opt,name=alert,proto3" json:"alert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertResponse) Reset() {
	*x = GetAlertResponse{}
	mi := &file_alert_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertResponse) ProtoMessage() {}

func (x *GetAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alert_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertResponse.ProtoReflect.Descriptor instead.
func (*GetAlertResponse) Descriptor() ([]byte, []int) {
	return file_alert_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetAlertResponse) GetAlert() *Alert {
	if x != nil {
		return x.Alert
	}
	return nil
}

type ListAlertsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertsRequest) Reset() {
	*x = ListAlertsRequest{}
	mi := &file_alert_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertsRequest) ProtoMessage() {}

func (x *ListAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertsRequest.ProtoReflect.Descriptor instead.
func (*ListAlertsRequest) Descriptor() ([]byte, []int) {
	return file_alert_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListAlertsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListAlertsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAlertsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type MarkAlertAsReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAlertAsReadRequest) Reset() {
	*x = MarkAlertAsReadRequest{}
	mi := &file_alert_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAlertAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAlertAsReadRequest) ProtoMessage() {}

func (x *MarkAlertAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAlertAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAlertAsReadRequest) Descriptor() ([]byte, []int) {
	return file_alert_service_proto_rawDescGZIP(), []int{4}
}

func (x *MarkAlertAsReadRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MarkAlertAsReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAlertAsReadResponse) Reset() {
	*x = MarkAlertAsReadResponse{}
	mi := &file_alert_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAlertAsReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAlertAsReadResponse) ProtoMessage() {}

func (x *MarkAlertAsReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alert_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAlertAsReadResponse.ProtoReflect.Descriptor instead.
func (*MarkAlertAsReadResponse) Descriptor() ([]byte, []int) {
	return file_alert_service_proto_rawDescGZIP(), []int{5}
}

func (x *MarkAlertAsReadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListAlertsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*Alert               `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertsResponse) Reset() {
	*x = ListAlertsResponse{}
	mi := &file_alert_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertsResponse) ProtoMessage() {}

func (x *ListAlertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alert_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertsResponse.ProtoReflect.Descriptor instead.
func (*ListAlertsResponse) Descriptor() ([]byte, []int) {
	return file_alert_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListAlertsResponse) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

func (x *ListAlertsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type AlertRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SensorId      int64                  `protobuf:"varint,3,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	ConditionType string                 `protobuf:"bytes,4,opt,name=condition_type,json=conditionType,proto3" json:"condition_type,omitempty"`
	Threshold     float64                `protobuf:"fixed64,5,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	IsEnabled     bool                   `protobuf:"varint,7,opt,name=is_enabled,json=isEnabled,proto3" json:"is_enabled,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UserId        int64                  `protobuf:"varint,9,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertRule) Reset() {
	*x = AlertRule{}
	mi := &file_alert_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertRule) ProtoMessage() {}

func (x *AlertRule) ProtoReflect() protoreflect.Message {
	mi := &file_alert_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertRule.ProtoReflect.Descriptor instead.
func (*AlertRule) Descriptor() ([]byte, []int) {
	return file_alert_service_proto_rawDescGZIP(), []int{7}
}

func (x *AlertRule) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AlertRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AlertRule) GetSensorId() int64 {
	if x != nil {
		return x.SensorId
	}
	return 0
}

func (x *AlertRule) GetConditionType() string {
	if x != nil {
		return x.ConditionType
	}
	return ""
}

func (x *AlertRule) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *AlertRule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AlertRule) GetIsEnabled() bool {
	if x != nil {
		return x.IsEnabled
	}
	return false
}

func (x *AlertRule) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AlertRule) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateAlertRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SensorId      int64                  `protobuf:"varint,2,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	ConditionType string                 `protobuf:"bytes,3,opt,name=condition_type,json=conditionType,proto3" json:"condition_type,omitempty"`
	Threshold     float64                `protobuf:"fixed64,4,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	UserId        int64                  `protobuf:"varint,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlertRuleRequest) Reset() {
	*x = CreateAlertRuleRequest{}
	mi := &file_alert_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlertRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlertRuleRequest) ProtoMessage() {}

func (x *CreateAlertRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlertRuleRequest.ProtoReflect.Descriptor instead.
func (*CreateAlertRuleRequest) Descriptor() ([]byte, []int) {
	return file_alert_service_proto_rawDescGZIP(), []int{8}
}

func (x *CreateAlertRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAlertRuleRequest) GetSensorId() int64 {
	if x != nil {
		return x.SensorId
	}
	return 0
}

func (x *CreateAlertRuleRequest) GetConditionType() string {
	if x != nil {
		return x.ConditionType
	}
	return ""
}

func (x *CreateAlertRuleRequest) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *CreateAlertRuleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAlertRuleRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateAlertRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertRule     *AlertRule             `protobuf:"bytes,1,opt,name=alert_rule,json=alertRule,proto3" json:"alert_rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlertRuleResponse) Reset() {
	*x = CreateAlertRuleResponse{}
	mi := &file_alert_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlertRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlertRuleResponse) ProtoMessage() {}

func (x *CreateAlertRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alert_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlertRuleResponse.ProtoReflect.Descriptor instead.
func (*CreateAlertRuleResponse) Descriptor() ([]byte, []int) {
	return file_alert_service_proto_rawDescGZIP(), []int{9}
}

func (x *CreateAlertRuleResponse) GetAlertRule() *AlertRule {
	if x != nil {
		return x.AlertRule
	}
	return nil
}

type GetAlertRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertRuleRequest) Reset() {
	*x = GetAlertRuleRequest{}
	mi := &file_alert_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertRuleRequest) ProtoMessage() {}

func (x *GetAlertRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertRuleRequest.ProtoReflect.Descriptor instead.
func (*GetAlertRuleRequest) Descriptor() ([]byte, []int) {
	return file_alert_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetAlertRuleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAlertRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertRule     *AlertRule             `protobuf:"bytes,1,opt,name=alert_rule,json=alertRule,proto3" json:"alert_rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertRuleResponse) Reset() {
	*x = GetAlertRuleResponse{}
	mi := &file_alert_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertRuleResponse) ProtoMessage() {}

func (x *GetAlertRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alert_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertRuleResponse.ProtoReflect.Descriptor instead.
func (*GetAlertRuleResponse) Descriptor() ([]byte, []int) {
	return file_alert_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetAlertRuleResponse) GetAlertRule() *AlertRule {
	if x != nil {
		return x.AlertRule
	}
	return nil
}

type ListAlertRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertRulesRequest) Reset() {
	*x = ListAlertRulesRequest{}
	mi := &file_alert_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertRulesRequest) ProtoMessage() {}

func (x *ListAlertRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertRulesRequest.ProtoReflect.Descriptor instead.
func (*ListAlertRulesRequest) Descriptor() ([]byte, []int) {
	return file_alert_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListAlertRulesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListAlertRulesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAlertRulesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListAlertRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertRules    []*AlertRule           `protobuf:"bytes,1,rep,name=alert_rules,json=alertRules,proto3" json:"alert_rules,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertRulesResponse) Reset() {
	*x = ListAlertRulesResponse{}
	mi := &file_alert_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertRulesResponse) ProtoMessage() {}

func (x *ListAlertRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alert_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertRulesResponse.ProtoReflect.Descriptor instead.
func (*ListAlertRulesResponse) Descriptor() ([]byte, []int) {
	return file_alert_service_proto_rawDescGZIP(), []int{13}
}

func (x *ListAlertRulesResponse) GetAlertRules() []*AlertRule {
	if x != nil {
		return x.AlertRules
	}
	return nil
}

func (x *ListAlertRulesResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type UpdateAlertRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SensorId      int64                  `protobuf:"varint,3,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	ConditionType string                 `protobuf:"bytes,4,opt,name=condition_type,json=conditionType,proto3" json:"condition_type,omitempty"`
	Threshold     float64                `protobuf:"fixed64,5,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	IsEnabled     bool                   `protobuf:"varint,7,opt,name=is_enabled,json=isEnabled,proto3" json:"is_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAlertRuleRequest) Reset() {
	*x = UpdateAlertRuleRequest{}
	mi := &file_alert_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAlertRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlertRuleRequest) ProtoMessage() {}

func (x *UpdateAlertRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlertRuleRequest.ProtoReflect.Descriptor instead.
func (*UpdateAlertRuleRequest) Descriptor() ([]byte, []int) {
	return file_alert_service_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateAlertRuleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAlertRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAlertRuleRequest) GetSensorId() int64 {
	if x != nil {
		return x.SensorId
	}
	return 0
}

func (x *UpdateAlertRuleRequest) GetConditionType() string {
	if x != nil {
		return x.ConditionType
	}
	return ""
}

func (x *UpdateAlertRuleRequest) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *UpdateAlertRuleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateAlertRuleRequest) GetIsEnabled() bool {
	if x != nil {
		return x.IsEnabled
	}
	return false
}

type UpdateAlertRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertRule     *AlertRule             `protobuf:"bytes,1,opt,name=alert_rule,json=alertRule,proto3" json:"alert_rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAlertRuleResponse) Reset() {
	*x = UpdateAlertRuleResponse{}
	mi := &file_alert_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAlertRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlertRuleResponse) ProtoMessage() {}

func (x *UpdateAlertRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alert_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlertRuleResponse.ProtoReflect.Descriptor instead.
func (*UpdateAlertRuleResponse) Descriptor() ([]byte, []int) {
	return file_alert_service_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateAlertRuleResponse) GetAlertRule() *AlertRule {
	if x != nil {
		return x.AlertRule
	}
	return nil
}

type DeleteAlertRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAlertRuleRequest) Reset() {
	*x = DeleteAlertRuleRequest{}
	mi := &file_alert_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAlertRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlertRuleRequest) ProtoMessage() {}

func (x *DeleteAlertRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlertRuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteAlertRuleRequest) Descriptor() ([]byte, []int) {
	return file_alert_service_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteAlertRuleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteAlertRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAlertRuleResponse) Reset() {
	*x = DeleteAlertRuleResponse{}
	mi := &file_alert_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAlertRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlertRuleResponse) ProtoMessage() {}

func (x *DeleteAlertRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alert_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlertRuleResponse.ProtoReflect.Descriptor instead.
func (*DeleteAlertRuleResponse) Descriptor() ([]byte, []int) {
	return file_alert_service_proto_rawDescGZIP(), []int{17}
}

var File_alert_service_proto protoreflect.FileDescriptor

const file_alert_service_proto_rawDesc = "" +
	"\n" +
	"\x13alert_service.proto\x12\ralert_service\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd5\x01\n" +
	"\x05Alert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\arule_id\x18\x02 \x01(\x03R\x06ruleId\x12\x1b\n" +
	"\tsensor_id\x18\x03 \x01(\x03R\bsensorId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x14\n" +
	"\x05value\x18\x05 \x01(\x01R\x05value\x12\x17\n" +
	"\ais_read\x18\x06 \x01(\bR\x06isRead\x12=\n" +
	"\ftriggered_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vtriggeredAt\"!\n" +
	"\x0fGetAlertRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\">\n" +
	"\x10GetAlertResponse\x12*\n" +
	"\x05alert\x18\x01 \x01(\v2\x14.alert_service.AlertR\x05alert\"Z\n" +
	"\x11ListAlertsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"(\n" +
	"\x16MarkAlertAsReadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"3\n" +
	"\x17MarkAlertAsReadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"c\n" +
	"\x12ListAlertsResponse\x12,\n" +
	"\x06alerts\x18\x01 \x03(\v2\x14.alert_service.AlertR\x06alerts\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"\xa6\x02\n" +
	"\tAlertRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tsensor_id\x18\x03 \x01(\x03R\bsensorId\x12%\n" +
	"\x0econdition_type\x18\x04 \x01(\tR\rconditionType\x12\x1c\n" +
	"\tthreshold\x18\x05 \x01(\x01R\tthreshold\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"is_enabled\x18\a \x01(\bR\tisEnabled\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x17\n" +
	"\auser_id\x18\t \x01(\x03R\x06userId\"\xc9\x01\n" +
	"\x16CreateAlertRuleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tsensor_id\x18\x02 \x01(\x03R\bsensorId\x12%\n" +
	"\x0econdition_type\x18\x03 \x01(\tR\rconditionType\x12\x1c\n" +
	"\tthreshold\x18\x04 \x01(\x01R\tthreshold\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\x03R\x06userId\"R\n" +
	"\x17CreateAlertRuleResponse\x127\n" +
	"\n" +
	"alert_rule\x18\x01 \x01(\v2\x18.alert_service.AlertRuleR\talertRule\"%\n" +
	"\x13GetAlertRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"O\n" +
	"\x14GetAlertRuleResponse\x127\n" +
	"\n" +
	"alert_rule\x18\x01 \x01(\v2\x18.alert_service.AlertRuleR\talertRule\"^\n" +
	"\x15ListAlertRulesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"t\n" +
	"\x16ListAlertRulesResponse\x129\n" +
	"\valert_rules\x18\x01 \x03(\v2\x18.alert_service.AlertRuleR\n" +
	"alertRules\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"\xdf\x01\n" +
	"\x16UpdateAlertRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tsensor_id\x18\x03 \x01(\x03R\bsensorId\x12%\n" +
	"\x0econdition_type\x18\x04 \x01(\tR\rconditionType\x12\x1c\n" +
	"\tthreshold\x18\x05 \x01(\x01R\tthreshold\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"is_enabled\x18\a \x01(\bR\tisEnabled\"R\n" +
	"\x17UpdateAlertRuleResponse\x127\n" +
	"\n" +
	"alert_rule\x18\x01 \x01(\v2\x18.alert_service.AlertRuleR\talertRule\"(\n" +
	"\x16DeleteAlertRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x19\n" +
	"\x17DeleteAlertRuleResponse2\xfe\x05\n" +
	"\fAlertService\x12M\n" +
	"\bGetAlert\x12\x1e.alert_service.GetAlertRequest\x1a\x1f.alert_service.GetAlertResponse\"\x00\x12S\n" +
	"\n" +
	"ListAlerts\x12 .alert_service.ListAlertsRequest\x1a!.alert_service.ListAlertsResponse\"\x00\x12b\n" +
	"\x0fMarkAlertAsRead\x12%.alert_service.MarkAlertAsReadRequest\x1a&.alert_service.MarkAlertAsReadResponse\"\x00\x12b\n" +
	"\x0fCreateAlertRule\x12%.alert_service.CreateAlertRuleRequest\x1a&.alert_service.CreateAlertRuleResponse\"\x00\x12Y\n" +
	"\fGetAlertRule\x12\".alert_service.GetAlertRuleRequest\x1a#.alert_service.GetAlertRuleResponse\"\x00\x12_\n" +
	"\x0eListAlertRules\x12$.alert_service.ListAlertRulesRequest\x1a%.alert_service.ListAlertRulesResponse\"\x00\x12b\n" +
	"\x0fUpdateAlertRule\x12%.alert_service.UpdateAlertRuleRequest\x1a&.alert_service.UpdateAlertRuleResponse\"\x00\x12b\n" +
	"\x0fDeleteAlertRule\x12%.alert_service.DeleteAlertRuleRequest\x1a&.alert_service.DeleteAlertRuleResponse\"\x00BFZDgithub.com/skni-kod/iot-monitor-backend/internal/proto/alert_serviceb\x06proto3"

var (
	file_alert_service_proto_rawDescOnce sync.Once
	file_alert_service_proto_rawDescData []byte
)

func file_alert_service_proto_rawDescGZIP() []byte {
	file_alert_service_proto_rawDescOnce.Do(func() {
		file_alert_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alert_service_proto_rawDesc), len(file_alert_service_proto_rawDesc)))
	})
	return file_alert_service_proto_rawDescData
}

var file_alert_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_alert_service_proto_goTypes = []any{
	(*Alert)(nil),                   // 0: alert_service.Alert
	(*GetAlertRequest)(nil),         // 1: alert_service.GetAlertRequest
	(*GetAlertResponse)(nil),        // 2: alert_service.GetAlertResponse
	(*ListAlertsRequest)(nil),       // 3: alert_service.ListAlertsRequest
	(*MarkAlertAsReadRequest)(nil),  // 4: alert_service.MarkAlertAsReadRequest
	(*MarkAlertAsReadResponse)(nil), // 5: alert_service.MarkAlertAsReadResponse
	(*ListAlertsResponse)(nil),      // 6: alert_service.ListAlertsResponse
	(*AlertRule)(nil),               // 7: alert_service.AlertRule
	(*CreateAlertRuleRequest)(nil),  // 8: alert_service.CreateAlertRuleRequest
	(*CreateAlertRuleResponse)(nil), // 9: alert_service.CreateAlertRuleResponse
	(*GetAlertRuleRequest)(nil),     // 10: alert_service.GetAlertRuleRequest
	(*GetAlertRuleResponse)(nil),    // 11: alert_service.GetAlertRuleResponse
	(*ListAlertRulesRequest)(nil),   // 12: alert_service.ListAlertRulesRequest
	(*ListAlertRulesResponse)(nil),  // 13: alert_service.ListAlertRulesResponse
	(*UpdateAlertRuleRequest)(nil),  // 14: alert_service.UpdateAlertRuleRequest
	(*UpdateAlertRuleResponse)(nil), // 15: alert_service.UpdateAlertRuleResponse
	(*DeleteAlertRuleRequest)(nil),  // 16: alert_service.DeleteAlertRuleRequest
	(*DeleteAlertRuleResponse)(nil), // 17: alert_service.DeleteAlertRuleResponse
	(*timestamppb.Timestamp)(nil),   // 18: google.protobuf.Timestamp
}
var file_alert_service_proto_depIdxs = []int32{
	18, // 0: alert_service.Alert.triggered_at:type_name -> google.protobuf.Timestamp
	0,  // 1: alert_service.GetAlertResponse.alert:type_name -> alert_service.Alert
	0,  // 2: alert_service.ListAlertsResponse.alerts:type_name -> alert_service.Alert
	18, // 3: alert_service.AlertRule.created_at:type_name -> google.protobuf.Timestamp
	7,  // 4: alert_service.CreateAlertRuleResponse.alert_rule:type_name -> alert_service.AlertRule
	7,  // 5: alert_service.GetAlertRuleResponse.alert_rule:type_name -> alert_service.AlertRule
	7,  // 6: alert_service.ListAlertRulesResponse.alert_rules:type_name -> alert_service.AlertRule
	7,  // 7: alert_service.UpdateAlertRuleResponse.alert_rule:type_name -> alert_service.AlertRule
	1,  // 8: alert_service.AlertService.GetAlert:input_type -> alert_service.GetAlertRequest
	3,  // 9: alert_service.AlertService.ListAlerts:input_type -> alert_service.ListAlertsRequest
	4,  // 10: alert_service.AlertService.MarkAlertAsRead:input_type -> alert_service.MarkAlertAsReadRequest
	8,  // 11: alert_service.AlertService.CreateAlertRule:input_type -> alert_service.CreateAlertRuleRequest
	10, // 12: alert_service.AlertService.GetAlertRule:input_type -> alert_service.GetAlertRuleRequest
	12, // 13: alert_service.AlertService.ListAlertRules:input_type -> alert_service.ListAlertRulesRequest
	14, // 14: alert_service.AlertService.UpdateAlertRule:input_type -> alert_service.UpdateAlertRuleRequest
	16, // 15: alert_service.AlertService.DeleteAlertRule:input_type -> alert_service.DeleteAlertRuleRequest
	2,  // 16: alert_service.AlertService.GetAlert:output_type -> alert_service.GetAlertResponse
	6,  // 17: alert_service.AlertService.ListAlerts:output_type -> alert_service.ListAlertsResponse
	5,  // 18: alert_service.AlertService.MarkAlertAsRead:output_type -> alert_service.MarkAlertAsReadResponse
	9,  // 19: alert_service.AlertService.CreateAlertRule:output_type -> alert_service.CreateAlertRuleResponse
	11, // 20: alert_service.AlertService.GetAlertRule:output_type -> alert_service.GetAlertRuleResponse
	13, // 21: alert_service.AlertService.ListAlertRules:output_type -> alert_service.ListAlertRulesResponse
	15, // 22: alert_service.AlertService.UpdateAlertRule:output_type -> alert_service.UpdateAlertRuleResponse
	17, // 23: alert_service.AlertService.DeleteAlertRule:output_type -> alert_service.DeleteAlertRuleResponse
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_alert_service_proto_init() }
func file_alert_service_proto_init() {
	if File_alert_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alert_service_proto_rawDesc), len(file_alert_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alert_service_proto_goTypes,
		DependencyIndexes: file_alert_service_proto_depIdxs,
		MessageInfos:      file_alert_service_proto_msgTypes,
	}.Build()
	File_alert_service_proto = out.File
	file_alert_service_proto_goTypes = nil
	file_alert_service_proto_depIdxs = nil
}
