// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/skni-kod/iot-monitor-backend/services/alert-service/ent/alert"
	"github.com/skni-kod/iot-monitor-backend/services/alert-service/ent/alertrule"
)

// Alert is the model entity for the Alert schema.
type Alert struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Value holds the value of the "value" field.
	Value float64 `json:"value,omitempty"`
	// Message holds the value of the "message" field.
	Message string `json:"message,omitempty"`
	// TriggeredAt holds the value of the "triggered_at" field.
	TriggeredAt time.Time `json:"triggered_at,omitempty"`
	// IsRead holds the value of the "is_read" field.
	IsRead bool `json:"is_read,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AlertQuery when eager-loading is set.
	Edges             AlertEdges `json:"edges"`
	alert_rule_alerts *int
	selectValues      sql.SelectValues
}

// AlertEdges holds the relations/edges for other nodes in the graph.
type AlertEdges struct {
	// Rule holds the value of the rule edge.
	Rule *AlertRule `json:"rule,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RuleOrErr returns the Rule value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AlertEdges) RuleOrErr() (*AlertRule, error) {
	if e.Rule != nil {
		return e.Rule, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: alertrule.Label}
	}
	return nil, &NotLoadedError{edge: "rule"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Alert) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case alert.FieldIsRead:
			values[i] = new(sql.NullBool)
		case alert.FieldValue:
			values[i] = new(sql.NullFloat64)
		case alert.FieldID:
			values[i] = new(sql.NullInt64)
		case alert.FieldMessage:
			values[i] = new(sql.NullString)
		case alert.FieldTriggeredAt:
			values[i] = new(sql.NullTime)
		case alert.ForeignKeys[0]: // alert_rule_alerts
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Alert fields.
func (a *Alert) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case alert.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			a.ID = int(value.Int64)
		case alert.FieldValue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				a.Value = value.Float64
			}
		case alert.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				a.Message = value.String
			}
		case alert.FieldTriggeredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field triggered_at", values[i])
			} else if value.Valid {
				a.TriggeredAt = value.Time
			}
		case alert.FieldIsRead:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_read", values[i])
			} else if value.Valid {
				a.IsRead = value.Bool
			}
		case alert.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field alert_rule_alerts", value)
			} else if value.Valid {
				a.alert_rule_alerts = new(int)
				*a.alert_rule_alerts = int(value.Int64)
			}
		default:
			a.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the Alert.
// This includes values selected through modifiers, order, etc.
func (a *Alert) GetValue(name string) (ent.Value, error) {
	return a.selectValues.Get(name)
}

// QueryRule queries the "rule" edge of the Alert entity.
func (a *Alert) QueryRule() *AlertRuleQuery {
	return NewAlertClient(a.config).QueryRule(a)
}

// Update returns a builder for updating this Alert.
// Note that you need to call Alert.Unwrap() before calling this method if this Alert
// was returned from a transaction, and the transaction was committed or rolled back.
func (a *Alert) Update() *AlertUpdateOne {
	return NewAlertClient(a.config).UpdateOne(a)
}

// Unwrap unwraps the Alert entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (a *Alert) Unwrap() *Alert {
	_tx, ok := a.config.driver.(*txDriver)
	if !ok {
		panic("ent: Alert is not a transactional entity")
	}
	a.config.driver = _tx.drv
	return a
}

// String implements the fmt.Stringer.
func (a *Alert) String() string {
	var builder strings.Builder
	builder.WriteString("Alert(")
	builder.WriteString(fmt.Sprintf("id=%v, ", a.ID))
	builder.WriteString("value=")
	builder.WriteString(fmt.Sprintf("%v", a.Value))
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(a.Message)
	builder.WriteString(", ")
	builder.WriteString("triggered_at=")
	builder.WriteString(a.TriggeredAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("is_read=")
	builder.WriteString(fmt.Sprintf("%v", a.IsRead))
	builder.WriteByte(')')
	return builder.String()
}

// Alerts is a parsable slice of Alert.
type Alerts []*Alert
