// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/skni-kod/iot-monitor-backend/services/alert-service/ent/alertrule"
	"github.com/skni-kod/iot-monitor-backend/services/alert-service/ent/predicate"
)

// AlertRuleDelete is the builder for deleting a AlertRule entity.
type AlertRuleDelete struct {
	config
	hooks    []Hook
	mutation *AlertRuleMutation
}

// Where appends a list predicates to the AlertRuleDelete builder.
func (ard *AlertRuleDelete) Where(ps ...predicate.AlertRule) *AlertRuleDelete {
	ard.mutation.Where(ps...)
	return ard
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ard *AlertRuleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ard.sqlExec, ard.mutation, ard.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ard *AlertRuleDelete) ExecX(ctx context.Context) int {
	n, err := ard.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ard *AlertRuleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(alertrule.Table, sqlgraph.NewFieldSpec(alertrule.FieldID, field.TypeInt))
	if ps := ard.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ard.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ard.mutation.done = true
	return affected, err
}

// AlertRuleDeleteOne is the builder for deleting a single AlertRule entity.
type AlertRuleDeleteOne struct {
	ard *AlertRuleDelete
}

// Where appends a list predicates to the AlertRuleDelete builder.
func (ardo *AlertRuleDeleteOne) Where(ps ...predicate.AlertRule) *AlertRuleDeleteOne {
	ardo.ard.mutation.Where(ps...)
	return ardo
}

// Exec executes the deletion query.
func (ardo *AlertRuleDeleteOne) Exec(ctx context.Context) error {
	n, err := ardo.ard.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{alertrule.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ardo *AlertRuleDeleteOne) ExecX(ctx context.Context) {
	if err := ardo.Exec(ctx); err != nil {
		panic(err)
	}
}
