// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/skni-kod/iot-monitor-backend/services/alert-service/ent/alert"
	"github.com/skni-kod/iot-monitor-backend/services/alert-service/ent/alertrule"
	"github.com/skni-kod/iot-monitor-backend/services/alert-service/ent/predicate"
)

// AlertRuleUpdate is the builder for updating AlertRule entities.
type AlertRuleUpdate struct {
	config
	hooks    []Hook
	mutation *AlertRuleMutation
}

// Where appends a list predicates to the AlertRuleUpdate builder.
func (aru *AlertRuleUpdate) Where(ps ...predicate.AlertRule) *AlertRuleUpdate {
	aru.mutation.Where(ps...)
	return aru
}

// SetName sets the "name" field.
func (aru *AlertRuleUpdate) SetName(s string) *AlertRuleUpdate {
	aru.mutation.SetName(s)
	return aru
}

// SetNillableName sets the "name" field if the given value is not nil.
func (aru *AlertRuleUpdate) SetNillableName(s *string) *AlertRuleUpdate {
	if s != nil {
		aru.SetName(*s)
	}
	return aru
}

// SetUserID sets the "user_id" field.
func (aru *AlertRuleUpdate) SetUserID(i int64) *AlertRuleUpdate {
	aru.mutation.ResetUserID()
	aru.mutation.SetUserID(i)
	return aru
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (aru *AlertRuleUpdate) SetNillableUserID(i *int64) *AlertRuleUpdate {
	if i != nil {
		aru.SetUserID(*i)
	}
	return aru
}

// AddUserID adds i to the "user_id" field.
func (aru *AlertRuleUpdate) AddUserID(i int64) *AlertRuleUpdate {
	aru.mutation.AddUserID(i)
	return aru
}

// SetSensorID sets the "sensor_id" field.
func (aru *AlertRuleUpdate) SetSensorID(i int64) *AlertRuleUpdate {
	aru.mutation.ResetSensorID()
	aru.mutation.SetSensorID(i)
	return aru
}

// SetNillableSensorID sets the "sensor_id" field if the given value is not nil.
func (aru *AlertRuleUpdate) SetNillableSensorID(i *int64) *AlertRuleUpdate {
	if i != nil {
		aru.SetSensorID(*i)
	}
	return aru
}

// AddSensorID adds i to the "sensor_id" field.
func (aru *AlertRuleUpdate) AddSensorID(i int64) *AlertRuleUpdate {
	aru.mutation.AddSensorID(i)
	return aru
}

// SetConditionType sets the "condition_type" field.
func (aru *AlertRuleUpdate) SetConditionType(s string) *AlertRuleUpdate {
	aru.mutation.SetConditionType(s)
	return aru
}

// SetNillableConditionType sets the "condition_type" field if the given value is not nil.
func (aru *AlertRuleUpdate) SetNillableConditionType(s *string) *AlertRuleUpdate {
	if s != nil {
		aru.SetConditionType(*s)
	}
	return aru
}

// SetThreshold sets the "threshold" field.
func (aru *AlertRuleUpdate) SetThreshold(f float64) *AlertRuleUpdate {
	aru.mutation.ResetThreshold()
	aru.mutation.SetThreshold(f)
	return aru
}

// SetNillableThreshold sets the "threshold" field if the given value is not nil.
func (aru *AlertRuleUpdate) SetNillableThreshold(f *float64) *AlertRuleUpdate {
	if f != nil {
		aru.SetThreshold(*f)
	}
	return aru
}

// AddThreshold adds f to the "threshold" field.
func (aru *AlertRuleUpdate) AddThreshold(f float64) *AlertRuleUpdate {
	aru.mutation.AddThreshold(f)
	return aru
}

// SetDescription sets the "description" field.
func (aru *AlertRuleUpdate) SetDescription(s string) *AlertRuleUpdate {
	aru.mutation.SetDescription(s)
	return aru
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (aru *AlertRuleUpdate) SetNillableDescription(s *string) *AlertRuleUpdate {
	if s != nil {
		aru.SetDescription(*s)
	}
	return aru
}

// ClearDescription clears the value of the "description" field.
func (aru *AlertRuleUpdate) ClearDescription() *AlertRuleUpdate {
	aru.mutation.ClearDescription()
	return aru
}

// SetIsEnabled sets the "is_enabled" field.
func (aru *AlertRuleUpdate) SetIsEnabled(b bool) *AlertRuleUpdate {
	aru.mutation.SetIsEnabled(b)
	return aru
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (aru *AlertRuleUpdate) SetNillableIsEnabled(b *bool) *AlertRuleUpdate {
	if b != nil {
		aru.SetIsEnabled(*b)
	}
	return aru
}

// SetCreatedAt sets the "created_at" field.
func (aru *AlertRuleUpdate) SetCreatedAt(t time.Time) *AlertRuleUpdate {
	aru.mutation.SetCreatedAt(t)
	return aru
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (aru *AlertRuleUpdate) SetNillableCreatedAt(t *time.Time) *AlertRuleUpdate {
	if t != nil {
		aru.SetCreatedAt(*t)
	}
	return aru
}

// AddAlertIDs adds the "alerts" edge to the Alert entity by IDs.
func (aru *AlertRuleUpdate) AddAlertIDs(ids ...int) *AlertRuleUpdate {
	aru.mutation.AddAlertIDs(ids...)
	return aru
}

// AddAlerts adds the "alerts" edges to the Alert entity.
func (aru *AlertRuleUpdate) AddAlerts(a ...*Alert) *AlertRuleUpdate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return aru.AddAlertIDs(ids...)
}

// Mutation returns the AlertRuleMutation object of the builder.
func (aru *AlertRuleUpdate) Mutation() *AlertRuleMutation {
	return aru.mutation
}

// ClearAlerts clears all "alerts" edges to the Alert entity.
func (aru *AlertRuleUpdate) ClearAlerts() *AlertRuleUpdate {
	aru.mutation.ClearAlerts()
	return aru
}

// RemoveAlertIDs removes the "alerts" edge to Alert entities by IDs.
func (aru *AlertRuleUpdate) RemoveAlertIDs(ids ...int) *AlertRuleUpdate {
	aru.mutation.RemoveAlertIDs(ids...)
	return aru
}

// RemoveAlerts removes "alerts" edges to Alert entities.
func (aru *AlertRuleUpdate) RemoveAlerts(a ...*Alert) *AlertRuleUpdate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return aru.RemoveAlertIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (aru *AlertRuleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, aru.sqlSave, aru.mutation, aru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (aru *AlertRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := aru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (aru *AlertRuleUpdate) Exec(ctx context.Context) error {
	_, err := aru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aru *AlertRuleUpdate) ExecX(ctx context.Context) {
	if err := aru.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aru *AlertRuleUpdate) check() error {
	if v, ok := aru.mutation.Name(); ok {
		if err := alertrule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AlertRule.name": %w`, err)}
		}
	}
	return nil
}

func (aru *AlertRuleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := aru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(alertrule.Table, alertrule.Columns, sqlgraph.NewFieldSpec(alertrule.FieldID, field.TypeInt))
	if ps := aru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aru.mutation.Name(); ok {
		_spec.SetField(alertrule.FieldName, field.TypeString, value)
	}
	if value, ok := aru.mutation.UserID(); ok {
		_spec.SetField(alertrule.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := aru.mutation.AddedUserID(); ok {
		_spec.AddField(alertrule.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := aru.mutation.SensorID(); ok {
		_spec.SetField(alertrule.FieldSensorID, field.TypeInt64, value)
	}
	if value, ok := aru.mutation.AddedSensorID(); ok {
		_spec.AddField(alertrule.FieldSensorID, field.TypeInt64, value)
	}
	if value, ok := aru.mutation.ConditionType(); ok {
		_spec.SetField(alertrule.FieldConditionType, field.TypeString, value)
	}
	if value, ok := aru.mutation.Threshold(); ok {
		_spec.SetField(alertrule.FieldThreshold, field.TypeFloat64, value)
	}
	if value, ok := aru.mutation.AddedThreshold(); ok {
		_spec.AddField(alertrule.FieldThreshold, field.TypeFloat64, value)
	}
	if value, ok := aru.mutation.Description(); ok {
		_spec.SetField(alertrule.FieldDescription, field.TypeString, value)
	}
	if aru.mutation.DescriptionCleared() {
		_spec.ClearField(alertrule.FieldDescription, field.TypeString)
	}
	if value, ok := aru.mutation.IsEnabled(); ok {
		_spec.SetField(alertrule.FieldIsEnabled, field.TypeBool, value)
	}
	if value, ok := aru.mutation.CreatedAt(); ok {
		_spec.SetField(alertrule.FieldCreatedAt, field.TypeTime, value)
	}
	if aru.mutation.AlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alertrule.AlertsTable,
			Columns: []string{alertrule.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aru.mutation.RemovedAlertsIDs(); len(nodes) > 0 && !aru.mutation.AlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alertrule.AlertsTable,
			Columns: []string{alertrule.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aru.mutation.AlertsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alertrule.AlertsTable,
			Columns: []string{alertrule.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, aru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{alertrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	aru.mutation.done = true
	return n, nil
}

// AlertRuleUpdateOne is the builder for updating a single AlertRule entity.
type AlertRuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AlertRuleMutation
}

// SetName sets the "name" field.
func (aruo *AlertRuleUpdateOne) SetName(s string) *AlertRuleUpdateOne {
	aruo.mutation.SetName(s)
	return aruo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (aruo *AlertRuleUpdateOne) SetNillableName(s *string) *AlertRuleUpdateOne {
	if s != nil {
		aruo.SetName(*s)
	}
	return aruo
}

// SetUserID sets the "user_id" field.
func (aruo *AlertRuleUpdateOne) SetUserID(i int64) *AlertRuleUpdateOne {
	aruo.mutation.ResetUserID()
	aruo.mutation.SetUserID(i)
	return aruo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (aruo *AlertRuleUpdateOne) SetNillableUserID(i *int64) *AlertRuleUpdateOne {
	if i != nil {
		aruo.SetUserID(*i)
	}
	return aruo
}

// AddUserID adds i to the "user_id" field.
func (aruo *AlertRuleUpdateOne) AddUserID(i int64) *AlertRuleUpdateOne {
	aruo.mutation.AddUserID(i)
	return aruo
}

// SetSensorID sets the "sensor_id" field.
func (aruo *AlertRuleUpdateOne) SetSensorID(i int64) *AlertRuleUpdateOne {
	aruo.mutation.ResetSensorID()
	aruo.mutation.SetSensorID(i)
	return aruo
}

// SetNillableSensorID sets the "sensor_id" field if the given value is not nil.
func (aruo *AlertRuleUpdateOne) SetNillableSensorID(i *int64) *AlertRuleUpdateOne {
	if i != nil {
		aruo.SetSensorID(*i)
	}
	return aruo
}

// AddSensorID adds i to the "sensor_id" field.
func (aruo *AlertRuleUpdateOne) AddSensorID(i int64) *AlertRuleUpdateOne {
	aruo.mutation.AddSensorID(i)
	return aruo
}

// SetConditionType sets the "condition_type" field.
func (aruo *AlertRuleUpdateOne) SetConditionType(s string) *AlertRuleUpdateOne {
	aruo.mutation.SetConditionType(s)
	return aruo
}

// SetNillableConditionType sets the "condition_type" field if the given value is not nil.
func (aruo *AlertRuleUpdateOne) SetNillableConditionType(s *string) *AlertRuleUpdateOne {
	if s != nil {
		aruo.SetConditionType(*s)
	}
	return aruo
}

// SetThreshold sets the "threshold" field.
func (aruo *AlertRuleUpdateOne) SetThreshold(f float64) *AlertRuleUpdateOne {
	aruo.mutation.ResetThreshold()
	aruo.mutation.SetThreshold(f)
	return aruo
}

// SetNillableThreshold sets the "threshold" field if the given value is not nil.
func (aruo *AlertRuleUpdateOne) SetNillableThreshold(f *float64) *AlertRuleUpdateOne {
	if f != nil {
		aruo.SetThreshold(*f)
	}
	return aruo
}

// AddThreshold adds f to the "threshold" field.
func (aruo *AlertRuleUpdateOne) AddThreshold(f float64) *AlertRuleUpdateOne {
	aruo.mutation.AddThreshold(f)
	return aruo
}

// SetDescription sets the "description" field.
func (aruo *AlertRuleUpdateOne) SetDescription(s string) *AlertRuleUpdateOne {
	aruo.mutation.SetDescription(s)
	return aruo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (aruo *AlertRuleUpdateOne) SetNillableDescription(s *string) *AlertRuleUpdateOne {
	if s != nil {
		aruo.SetDescription(*s)
	}
	return aruo
}

// ClearDescription clears the value of the "description" field.
func (aruo *AlertRuleUpdateOne) ClearDescription() *AlertRuleUpdateOne {
	aruo.mutation.ClearDescription()
	return aruo
}

// SetIsEnabled sets the "is_enabled" field.
func (aruo *AlertRuleUpdateOne) SetIsEnabled(b bool) *AlertRuleUpdateOne {
	aruo.mutation.SetIsEnabled(b)
	return aruo
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (aruo *AlertRuleUpdateOne) SetNillableIsEnabled(b *bool) *AlertRuleUpdateOne {
	if b != nil {
		aruo.SetIsEnabled(*b)
	}
	return aruo
}

// SetCreatedAt sets the "created_at" field.
func (aruo *AlertRuleUpdateOne) SetCreatedAt(t time.Time) *AlertRuleUpdateOne {
	aruo.mutation.SetCreatedAt(t)
	return aruo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (aruo *AlertRuleUpdateOne) SetNillableCreatedAt(t *time.Time) *AlertRuleUpdateOne {
	if t != nil {
		aruo.SetCreatedAt(*t)
	}
	return aruo
}

// AddAlertIDs adds the "alerts" edge to the Alert entity by IDs.
func (aruo *AlertRuleUpdateOne) AddAlertIDs(ids ...int) *AlertRuleUpdateOne {
	aruo.mutation.AddAlertIDs(ids...)
	return aruo
}

// AddAlerts adds the "alerts" edges to the Alert entity.
func (aruo *AlertRuleUpdateOne) AddAlerts(a ...*Alert) *AlertRuleUpdateOne {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return aruo.AddAlertIDs(ids...)
}

// Mutation returns the AlertRuleMutation object of the builder.
func (aruo *AlertRuleUpdateOne) Mutation() *AlertRuleMutation {
	return aruo.mutation
}

// ClearAlerts clears all "alerts" edges to the Alert entity.
func (aruo *AlertRuleUpdateOne) ClearAlerts() *AlertRuleUpdateOne {
	aruo.mutation.ClearAlerts()
	return aruo
}

// RemoveAlertIDs removes the "alerts" edge to Alert entities by IDs.
func (aruo *AlertRuleUpdateOne) RemoveAlertIDs(ids ...int) *AlertRuleUpdateOne {
	aruo.mutation.RemoveAlertIDs(ids...)
	return aruo
}

// RemoveAlerts removes "alerts" edges to Alert entities.
func (aruo *AlertRuleUpdateOne) RemoveAlerts(a ...*Alert) *AlertRuleUpdateOne {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return aruo.RemoveAlertIDs(ids...)
}

// Where appends a list predicates to the AlertRuleUpdate builder.
func (aruo *AlertRuleUpdateOne) Where(ps ...predicate.AlertRule) *AlertRuleUpdateOne {
	aruo.mutation.Where(ps...)
	return aruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (aruo *AlertRuleUpdateOne) Select(field string, fields ...string) *AlertRuleUpdateOne {
	aruo.fields = append([]string{field}, fields...)
	return aruo
}

// Save executes the query and returns the updated AlertRule entity.
func (aruo *AlertRuleUpdateOne) Save(ctx context.Context) (*AlertRule, error) {
	return withHooks(ctx, aruo.sqlSave, aruo.mutation, aruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (aruo *AlertRuleUpdateOne) SaveX(ctx context.Context) *AlertRule {
	node, err := aruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (aruo *AlertRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := aruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aruo *AlertRuleUpdateOne) ExecX(ctx context.Context) {
	if err := aruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aruo *AlertRuleUpdateOne) check() error {
	if v, ok := aruo.mutation.Name(); ok {
		if err := alertrule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AlertRule.name": %w`, err)}
		}
	}
	return nil
}

func (aruo *AlertRuleUpdateOne) sqlSave(ctx context.Context) (_node *AlertRule, err error) {
	if err := aruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(alertrule.Table, alertrule.Columns, sqlgraph.NewFieldSpec(alertrule.FieldID, field.TypeInt))
	id, ok := aruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AlertRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := aruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, alertrule.FieldID)
		for _, f := range fields {
			if !alertrule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != alertrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := aruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aruo.mutation.Name(); ok {
		_spec.SetField(alertrule.FieldName, field.TypeString, value)
	}
	if value, ok := aruo.mutation.UserID(); ok {
		_spec.SetField(alertrule.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := aruo.mutation.AddedUserID(); ok {
		_spec.AddField(alertrule.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := aruo.mutation.SensorID(); ok {
		_spec.SetField(alertrule.FieldSensorID, field.TypeInt64, value)
	}
	if value, ok := aruo.mutation.AddedSensorID(); ok {
		_spec.AddField(alertrule.FieldSensorID, field.TypeInt64, value)
	}
	if value, ok := aruo.mutation.ConditionType(); ok {
		_spec.SetField(alertrule.FieldConditionType, field.TypeString, value)
	}
	if value, ok := aruo.mutation.Threshold(); ok {
		_spec.SetField(alertrule.FieldThreshold, field.TypeFloat64, value)
	}
	if value, ok := aruo.mutation.AddedThreshold(); ok {
		_spec.AddField(alertrule.FieldThreshold, field.TypeFloat64, value)
	}
	if value, ok := aruo.mutation.Description(); ok {
		_spec.SetField(alertrule.FieldDescription, field.TypeString, value)
	}
	if aruo.mutation.DescriptionCleared() {
		_spec.ClearField(alertrule.FieldDescription, field.TypeString)
	}
	if value, ok := aruo.mutation.IsEnabled(); ok {
		_spec.SetField(alertrule.FieldIsEnabled, field.TypeBool, value)
	}
	if value, ok := aruo.mutation.CreatedAt(); ok {
		_spec.SetField(alertrule.FieldCreatedAt, field.TypeTime, value)
	}
	if aruo.mutation.AlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alertrule.AlertsTable,
			Columns: []string{alertrule.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aruo.mutation.RemovedAlertsIDs(); len(nodes) > 0 && !aruo.mutation.AlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alertrule.AlertsTable,
			Columns: []string{alertrule.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aruo.mutation.AlertsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alertrule.AlertsTable,
			Columns: []string{alertrule.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AlertRule{config: aruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, aruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{alertrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	aruo.mutation.done = true
	return _node, nil
}
