// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/skni-kod/iot-monitor-backend/services/alert-service/ent/alert"
	"github.com/skni-kod/iot-monitor-backend/services/alert-service/ent/alertrule"
	"github.com/skni-kod/iot-monitor-backend/services/alert-service/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	alertFields := schema.Alert{}.Fields()
	_ = alertFields
	// alertDescTriggeredAt is the schema descriptor for triggered_at field.
	alertDescTriggeredAt := alertFields[3].Descriptor()
	// alert.DefaultTriggeredAt holds the default value on creation for the triggered_at field.
	alert.DefaultTriggeredAt = alertDescTriggeredAt.Default.(func() time.Time)
	// alertDescIsRead is the schema descriptor for is_read field.
	alertDescIsRead := alertFields[4].Descriptor()
	// alert.DefaultIsRead holds the default value on creation for the is_read field.
	alert.DefaultIsRead = alertDescIsRead.Default.(bool)
	alertruleFields := schema.AlertRule{}.Fields()
	_ = alertruleFields
	// alertruleDescName is the schema descriptor for name field.
	alertruleDescName := alertruleFields[0].Descriptor()
	// alertrule.NameValidator is a validator for the "name" field. It is called by the builders before save.
	alertrule.NameValidator = alertruleDescName.Validators[0].(func(string) error)
	// alertruleDescConditionType is the schema descriptor for condition_type field.
	alertruleDescConditionType := alertruleFields[3].Descriptor()
	// alertrule.DefaultConditionType holds the default value on creation for the condition_type field.
	alertrule.DefaultConditionType = alertruleDescConditionType.Default.(string)
	// alertruleDescIsEnabled is the schema descriptor for is_enabled field.
	alertruleDescIsEnabled := alertruleFields[6].Descriptor()
	// alertrule.DefaultIsEnabled holds the default value on creation for the is_enabled field.
	alertrule.DefaultIsEnabled = alertruleDescIsEnabled.Default.(bool)
	// alertruleDescCreatedAt is the schema descriptor for created_at field.
	alertruleDescCreatedAt := alertruleFields[7].Descriptor()
	// alertrule.DefaultCreatedAt holds the default value on creation for the created_at field.
	alertrule.DefaultCreatedAt = alertruleDescCreatedAt.Default.(func() time.Time)
}
